### PR TITLE
new entities on backend and state management on client

### PR DESCRIPTION
**Pull request by bright258**
Created entities and a few services for Corner, Update, Wallet, Followers.... Ran migrations.... Done state management on React frontend.... About to wire up more pages and complete all necessary services. Also, considering using Emailjs to send onboarding message to new sign ups

### CODE REVIEW

**Comment by 3cognito** [comment]
I will create a staging branch and set it to the default branch. Only stable and tested changes will be merged into main. After I merge this pending PR. Also I am yet to do any comprehensive reviews because I want you to feel comfortable with Nestjs first.

**Review by 3cognito — APPROVED** [review]

**Comment by 3cognito** [comment]
On the next PR, I will attempting running the backend server, my hope is that by then the server should be running and some routes should be properly wired up.

**Comment by bright258** [comment]
Alright. Noted

**Comment by 3cognito** [comment]
I cannot set the staging branch to the default. I think only you can

**Comment by bright258** [comment]
Alright. I will do that right away

**Comment by bright258** [comment]
Done

**Comment by 3cognito** [comment]
Okay. So merges to main will only be done after things are confirmed to be
working on staging. You can even deploy the staging server if you want.
Anytime.

**Comment by bright258** [comment]
Noted. Thank you

**Pull request merged**
